
## 第一部分： 基础信息
name: helloworld_demo                               # <必选项> 包名称
version: master                                    # <必选项> 组件版本号
description: HaaS100 LED blink helloworld example        # <必选项> 建议至少20字以上
type: solution                                      # <必选项> 组件类型，为：solution, chip, board, common, sdk

solution:
  cpu_id: cpu0
  board_name: haas100
  toolchain_prefix: arm-none-eabi
  toolchain_path: "D:/arm-none-eabi-tc"

## 第二部分：依赖信息
depends:
  - haas100: master
  - init: master
  - cli: master
  - osal_aos: master
  - posix: master

supported_boards:
  - haas100: master

## 第四部分：编译连接信息
build_config:
  cflag: -include aos_compat.h -Wno-implicit-function-declaration -Wno-implicit-int -Wno-error=incompatible-pointer-types -Wno-error=int-conversion

source_file:
  - "maintask.c"
  - "helloworld.c"

## 第五部分：配置信息
def_config:
  CLI_CONFIG_STACK_SIZE: 8192
